language: ruby
rvm:
  - 2.6.5
before_install:
  - yarn config set ignore-engines true
before_script:
  - bin/rails db:setup RAILS_ENV=test
  - bin/rails assets:precompile
script:
  - bin/rails ci
cache: bundler
services:
  - postgresql
