language: ruby
rvm:
  - 2.6.5
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - bin/rails db:setup RAILS_ENV=test
  - bin/rails assets:precompile
script:
  - bin/rails ci
cache: bundler
services:
  - postgresql
